name: Tests

on: [push, workflow_dispatch]

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Upload news to Discord
      run: |
          if [ ! -z ${{ secrets.NEWS_WEBHOOK_URL }}; then
            NEWS_CONTENT=$( git diff ${{ github.event.before }} NEWS.md )
            if [ ! -z NEWS_CONTENT ]; then
                NEWS_JSON=$( echo '{}' | jq -c --arg news "$NEWS_CONTENT" \
                                               --arg commit "${{ github.event.after }}" \
                                               --arg date "$(date)" \
                                               '{ content : ($commit + " on " + $date + "\n\n```patch" + $news + "```") }' )
                curl -H "Content-Type: application/json" -d "$NEWS_JSON" "${{ secrets.NEWS_WEBHOOK_URL }}"
            fi
          fi
    - name: Trigger BE build
      if: ${{ github.repository == 'code-explorer786/Mindustry' }}
      run: |
        git clone --depth=1 --branch=master https://github.com/code-explorer786/MindustryBuilds ../MindustryBuilds
        cd ../MindustryBuilds
        BNUM=$(($GITHUB_RUN_NUMBER + 30000))
        git tag ${BNUM}
        git config --global user.name "Github Actions"
        git push https://code-explorer786:${{ secrets.API_TOKEN_GITHUB }}@github.com/code-explorer786/MindustryBuilds ${BNUM}
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run unit tests
      run: ./gradlew clean cleanTest test --stacktrace
