name: Tests

on: [push, workflow_dispatch]

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          # Please bump this number, and replace HEAD~20.
          fetch-depth : 20
    - name: Upload news to Discord and Matrix
      run: |
          NEWS_CONTENT=$( git diff ${{ github.event.before }} NEWS.md ) || NEWS_CONTENT=$( git diff HEAD~20 NEWS.md )
          if [ ! -z "$NEWS_CONTENT" ]; then
              if [ ! -z "${{ secrets.NEWS_WEBHOOK_URL  }}" ]; then
                NEWS_JSON=$( echo '{}' | jq -c --arg news "$NEWS_CONTENT" \
                                                 --arg commit "${{ github.event.after }}" \
                                                 --arg date "$(date)" \
                                                 '{ content : ("`" + $commit + "` on `" + $date + "`\n\n```patch\n" + $news + "```") }' )
                url --json "$NEWS_JSON" "${{ secrets.NEWS_WEBHOOK_URL }}"
              fi

              # Thanks DeltaNedas!
              if [ ! -z "${{ secrets.MATRIX_NEWS_WEBHOOK_URL  }}" ]; then
                NEWS_JSON=$( echo '{}' | jq -c --arg news "$NEWS_CONTENT" \
                                                 --arg commit "${{ github.event.after }}" \
                                                 --arg date "$(date)" \
                                                 '{' \
                                                     'formatted_body: ("<p><code>" + $commit + "</code> on <code>" + $date + "</code></p>\n\n<pre><code>patch\n" + $news + "</code></pre>"),' \
                                                    'body: ("`" + $commit + "` on `" + $date + "`\n\n```patch\n" + $news + "```"),' \
                                                    'msgtype: "m.notice","format":"org.matrix.custom.html"' \
                                                 '}' )
                url --json "$NEWS_JSON" "${{ secrets.MATRIX_NEWS_WEBHOOK_URL }}"
              fi
          fi
    - name: Trigger BE build
      if: ${{ github.repository == 'code-explorer786/Mindustry' }}
      run: |
        git clone --depth=1 --branch=master https://github.com/code-explorer786/MindustryBuilds ../MindustryBuilds
        cd ../MindustryBuilds
        BNUM=$(($GITHUB_RUN_NUMBER + 30000))
        git tag ${BNUM}
        git config --global user.name "Github Actions"
        git push https://code-explorer786:${{ secrets.API_TOKEN_GITHUB }}@github.com/code-explorer786/MindustryBuilds ${BNUM}
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run unit tests
      run: ./gradlew clean cleanTest test --stacktrace
